# Generated by Django 3.0.7 on 2020-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('S', 'Shoe'), ('E', 'Electronics'), ('F', 'Food'), ('M', 'Men'), ('B', 'Books'), ('C', 'Cars')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images')),
            ],
        ),
    ]
